//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_AdviceFeedback
    {
        public string Id { get; set; }
        public string StudentsRealName { get; set; }
        public string StudentsName { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string ProfessionalBaseCode { get; set; }
        public string ProfessionalBaseName { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string RegisterDate { get; set; }
        public string Writor { get; set; }
        public string TeacherCheck { get; set; }
        public string KzrCheck { get; set; }
        public string BaseCheck { get; set; }
        public string ManagerCheck { get; set; }
        public string TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string Comment { get; set; }
        public string FeedbackInformation { get; set; }
        public string ManagerReply { get; set; }
        public string ManagerName { get; set; }
        public string ManagerDate { get; set; }
        public string ManagerHandle { get; set; }
    }
}
