//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_BigMedicalRecords2
    {
        public string Id { get; set; }
        public string StudentsRealName { get; set; }
        public string StudentsName { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string ProfessionalBaseCode { get; set; }
        public string ProfessionalBaseName { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string RegisterDate { get; set; }
        public string Writor { get; set; }
        public string TeacherCheck { get; set; }
        public string KzrCheck { get; set; }
        public string BaseCheck { get; set; }
        public string ManagerCheck { get; set; }
        public string TeachersName { get; set; }
        public string TeachersRealName { get; set; }
        public string PatientNo { get; set; }
        public string InhospitalNo { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string Job { get; set; }
        public string Nation { get; set; }
        public string Marriage { get; set; }
        public string BirthProvinceCode { get; set; }
        public string BirthProvinceName { get; set; }
        public string BirthCityCode { get; set; }
        public string BirthCityName { get; set; }
        public string BirthAreaCode { get; set; }
        public string BirthAreaName { get; set; }
        public string BirthDetailAddress { get; set; }
        public string Company { get; set; }
        public string NowProvinceCode { get; set; }
        public string NowProvinceName { get; set; }
        public string NowCityCode { get; set; }
        public string NowCityName { get; set; }
        public string NowAreaCode { get; set; }
        public string NowAreaName { get; set; }
        public string NowDetailAddress { get; set; }
        public string Phone { get; set; }
        public string InhospitalDate { get; set; }
        public string RecordDate { get; set; }
        public string MedicalHistorySpeaker { get; set; }
        public string ReliableDegree { get; set; }
        public string ZhuSu { get; set; }
        public string XBShi_FBQK { get; set; }
        public string XBShi_ZYZZ { get; set; }
        public string XBShi_BSZZ { get; set; }
        public string XBShi_FBYL { get; set; }
        public string XBShi_FBYLY { get; set; }
        public string XBShi_QT { get; set; }
        public string JWShi_YBJK { get; set; }
        public string JWShi_JBS { get; set; }
        public string JWShi_CRBS { get; set; }
        public string JWShi_YFJZ { get; set; }
        public string JWShi_SSWS { get; set; }
        public string JWShi_SXS { get; set; }
        public string JWShi_SWYW { get; set; }
        public string JWShi_QT { get; set; }
        public string XTHGu_HXXT { get; set; }
        public string XTHGu_XHXT { get; set; }
        public string XTHGu_XHuaXT { get; set; }
        public string XTHGu_MNXT { get; set; }
        public string XTHGu_ZXXT { get; set; }
        public string XTHGu_NFMXT { get; set; }
        public string XTHGu_SJJS { get; set; }
        public string XTHGu_JRGG { get; set; }
        public string GRShi { get; set; }
        public string HYShi { get; set; }
        public string YJShi { get; set; }
        public string SYShi { get; set; }
        public string JZShi { get; set; }
        public string TGJCha_SMTZ_TiWen { get; set; }
        public string TGJCha_SMTZ_MaiBo { get; set; }
        public string TGJCha_SMTZ_HuXi { get; set; }
        public string TGJCha_SMTZ_XueYa1 { get; set; }
        public string TGJCha_SMTZ_XueYa2 { get; set; }
        public string TGJCha_SMTZ_TiZhong { get; set; }
        public string TGJCha_YBZK { get; set; }
        public string TGJCha_PFNM { get; set; }
        public string TGJCha_LBJ { get; set; }
        public string TGJCha_TB_TL { get; set; }
        public string TGJCha_TB_Y { get; set; }
        public string TGJCha_TB_E { get; set; }
        public string TGJCha_TB_B { get; set; }
        public string TGJCha_TB_KQ { get; set; }
        public string TGJCha_JB { get; set; }
        public string TGJCha_XB { get; set; }
        public string TGJCha_F_SZ { get; set; }
        public string TGJCha_F_CZ { get; set; }
        public string TGJCha_F_KZ { get; set; }
        public string TGJCha_F_TZ { get; set; }
        public string TGJCha_X_SZ { get; set; }
        public string TGJCha_X_CZ { get; set; }
        public string TGJCha_X_KZ { get; set; }
        public string TGJCha_X_TZ { get; set; }
        public string TGJCha_NDM { get; set; }
        public string TGJCha_ZWXG { get; set; }
        public string TGJCha_FB_FW { get; set; }
        public string TGJCha_FB_SZ { get; set; }
        public string TGJCha_FB_CZ { get; set; }
        public string TGJCha_FB_GZ { get; set; }
        public string TGJCha_FB_DN { get; set; }
        public string TGJCha_FB_PZ { get; set; }
        public string TGJCha_FB_ShenZ { get; set; }
        public string TGJCha_FB_PG { get; set; }
        public string TGJCha_FB_KZ { get; set; }
        public string TGJCha_FB_TZ { get; set; }
        public string TGJCha_GMZC { get; set; }
        public string TGJCha_WSZQ { get; set; }
        public string TGJCha_JZ { get; set; }
        public string TGJCha_SZ { get; set; }
        public string TGJCha_SJFS_SLFS { get; set; }
        public string TGJCha_SJFS_BLFS { get; set; }
        public string TGJCha_SJFS_NMCJ { get; set; }
        public string TGJCha_SJFS_QT { get; set; }
        public string TGJCha_ZKQK { get; set; }
        public string SYSQXie { get; set; }
        public string BLZYao { get; set; }
        public string CBZDuan { get; set; }
        public string RYZDuan { get; set; }
        public string XZZDuan { get; set; }
        public string Reviewer { get; set; }
        public string ReviewerDate { get; set; }
        public string RecordsStatus { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
    }
}
