//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Disease_Register
    {
        public string id { get; set; }
        public string professional_base_code { get; set; }
        public string professional_base_name { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
        public string dept_time { get; set; }
        public string is_required { get; set; }
        public string disease_code { get; set; }
        public string disease_name { get; set; }
        public string required_num { get; set; }
        public string master_degree { get; set; }
        public string manage_patient { get; set; }
        public string full_manage { get; set; }
        public string outpatient { get; set; }
    }
}
