//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Disease_Register2
    {
        public string id { get; set; }
        public string students_name { get; set; }
        public string students_real_name { get; set; }
        public string training_base_name { get; set; }
        public string professional_base_name { get; set; }
        public string dept_name { get; set; }
        public string disease_name { get; set; }
        public string required_num { get; set; }
        public string real_num { get; set; }
        public string master_degree { get; set; }
        public string patient_name { get; set; }
        public string case_num { get; set; }
        public string main_diagnosis { get; set; }
        public string secondary_diagnosis { get; set; }
        public string is_charge { get; set; }
        public string is_rescue { get; set; }
        public string cure_measure { get; set; }
        public string visit_date { get; set; }
        public string comment { get; set; }
        public string writor { get; set; }
        public string register_date { get; set; }
        public string training_base_code { get; set; }
        public string professional_base_code { get; set; }
        public string dept_code { get; set; }
        public string teacher_check { get; set; }
        public string kzr_check { get; set; }
        public string base_check { get; set; }
        public string manage_check { get; set; }
        public string condition { get; set; }
        public string TeacherId { get; set; }
        public string TeacherName { get; set; }
    }
}
