//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_DeptManagement
    {
        public string Id { get; set; }
        public string ManagersName { get; set; }
        public string ManagersRealName { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string ProfessionalBaseCode { get; set; }
        public string ProfessionalBaseName { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string DeptTime { get; set; }
        public string RealTime { get; set; }
        public string IsRequired { get; set; }
        public string TrainingTime { get; set; }
        public string TotalDeptTime { get; set; }
        public string TotalRealTime { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
    }
}
