//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_NeiKeOption
    {
        public string SubjectName { get; set; }
        public string Question { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string OptionE { get; set; }
        public string CorrectAnswer { get; set; }
        public string SubjectCode { get; set; }
        public string QuestionType { get; set; }
        public string Tag1 { get; set; }
        public string Id { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
    }
}
