//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_OutDept_Exam
    {
        public string id { get; set; }
        public string students_name { get; set; }
        public string students_real_name { get; set; }
        public string sex { get; set; }
        public string training_base_code { get; set; }
        public string training_base_name { get; set; }
        public string high_education { get; set; }
        public string high_education_time { get; set; }
        public string professional_base_code { get; set; }
        public string professional_base_name { get; set; }
        public string rotary_dept_code { get; set; }
        public string rotary_dept_name { get; set; }
        public string rotary_begin_time { get; set; }
        public string rotary_end_time { get; set; }
        public string instructor { get; set; }
        public string instructor_tag { get; set; }
        public string kqqk { get; set; }
        public string gztd { get; set; }
        public string ydyf { get; set; }
        public string llsp { get; set; }
        public string zdzx { get; set; }
        public string blsx { get; set; }
        public string clbrnl { get; set; }
        public string sjcznl { get; set; }
        public string czjn { get; set; }
        public string zdsp { get; set; }
        public string djnl { get; set; }
        public string total_score { get; set; }
        public string instructor_date { get; set; }
        public string is_pass { get; set; }
        public string dept_manager { get; set; }
        public string dept_manager_date { get; set; }
    }
}
