//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Questionnaire
    {
        public string id { get; set; }
        public string training_base_name { get; set; }
        public string training_base_code { get; set; }
        public string professional_base_name { get; set; }
        public string professional_base_code { get; set; }
        public string rotary_dept_name { get; set; }
        public string rotary_dept_code { get; set; }
        public string instructor { get; set; }
        public string one { get; set; }
        public string two { get; set; }
        public string three { get; set; }
        public string four { get; set; }
        public string five { get; set; }
        public string six { get; set; }
        public string seven { get; set; }
        public string eight { get; set; }
        public string nine { get; set; }
        public string ten { get; set; }
        public string eleven { get; set; }
        public string twelve { get; set; }
        public string thirteen { get; set; }
        public string advice { get; set; }
        public string register_date { get; set; }
        public string writor { get; set; }
    }
}
