//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_RotarySchedule
    {
        public string Id { get; set; }
        public string ManagersName { get; set; }
        public string ManagersRealName { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string ProfessionalBaseCode { get; set; }
        public string ProfessionalBaseName { get; set; }
        public string BeginTimeList { get; set; }
        public string EndTimeList { get; set; }
        public string DaysList { get; set; }
        public string DeptCodeList { get; set; }
        public string DeptNameList { get; set; }
        public Nullable<int> SchemeOrder { get; set; }
        public string RotaryBeginTime { get; set; }
        public string RotaryEndTime { get; set; }
        public string TotalRealTime { get; set; }
        public string TrainingTime { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
    }
}
