//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_StudentsPersonalInformation2
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string RealName { get; set; }
        public string ImagePath { get; set; }
        public string Sex { get; set; }
        public string IdNumber { get; set; }
        public string DateBirth { get; set; }
        public string MinZu { get; set; }
        public string Telephon { get; set; }
        public string Mail { get; set; }
        public string BkSchool { get; set; }
        public string BkMajor { get; set; }
        public string GraduationTime { get; set; }
        public string HighEducation { get; set; }
        public string HighSchool { get; set; }
        public string HighMajor { get; set; }
        public string HighEducationTime { get; set; }
        public string IdentityType { get; set; }
        public string SendUnit { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string CollaborativeUnit { get; set; }
        public string ProfessionalBaseCode { get; set; }
        public string ProfessionalBaseName { get; set; }
        public string TrainingTime { get; set; }
        public string PlanTrainingTime { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
        public string TrainingBaseProvinceCode { get; set; }
        public string TrainingBaseProvinceName { get; set; }
    }
}
