//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_SchoolInformation
    {
        public string Id { get; set; }
        public string ProvinceName { get; set; }
        public string SchoolName { get; set; }
        public string ManageUnit { get; set; }
        public string CityName { get; set; }
        public string SchoolLevel { get; set; }
        public string SchoolType { get; set; }
        public string Tag1 { get; set; }
    }
}
