//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_StudentsRotaryInformation2
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string RealName { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string ProfessionalBaseCode { get; set; }
        public string ProfessionalBaseName { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string RotaryBeginTime { get; set; }
        public string RotaryEndTime { get; set; }
        public string RotaryDays { get; set; }
        public Nullable<int> RotaryOrder { get; set; }
        public string TeachersName { get; set; }
        public string TeachersRealName { get; set; }
        public string OutdeptStatus { get; set; }
        public string OutdeptApplication { get; set; }
        public string QuestionnaireStatus { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
    }
}
