//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_TiKuResult
    {
        public string Id { get; set; }
        public string StudentsName { get; set; }
        public string StudentsRealName { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string SubjectName { get; set; }
        public string SubjectCode { get; set; }
        public string TotalScore { get; set; }
        public string TotalNum { get; set; }
        public string UndoNum { get; set; }
        public string CorrectNum { get; set; }
        public string ErrorNum { get; set; }
        public string RegisterDate { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
    }
}
