//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_TeachingActivities
    {
        public string Id { get; set; }
        public string StudentsRealName { get; set; }
        public string StudentsName { get; set; }
        public string TrainingBaseCode { get; set; }
        public string TrainingBaseName { get; set; }
        public string ProfessionalBaseCode { get; set; }
        public string ProfessionalBaseName { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string RegisterDate { get; set; }
        public string Writor { get; set; }
        public string TeacherCheck { get; set; }
        public string KzrCheck { get; set; }
        public string BaseCheck { get; set; }
        public string ManagerCheck { get; set; }
        public string TeachersName { get; set; }
        public string TeachersRealName { get; set; }
        public string ActivityForm { get; set; }
        public string ActivityContent { get; set; }
        public string MainSpeaker { get; set; }
        public string ClassHour { get; set; }
        public string ActivityDate { get; set; }
        public string Comment { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
    }
}
