//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Teachers_Appoint_Information
    {
        public string id { get; set; }
        public string teachers_name { get; set; }
        public string teachers_real_name { get; set; }
        public string appoint_begin_time { get; set; }
        public string appoint_end_time { get; set; }
        public string training_content { get; set; }
        public string total_num { get; set; }
        public string class_num { get; set; }
        public string each_class_num { get; set; }
        public string comment { get; set; }
        public string is_pass { get; set; }
        public string type { get; set; }
        public string training_base_code { get; set; }
        public string training_base_name { get; set; }
        public string professional_base_code { get; set; }
        public string professional_base_name { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
        public string register_date { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string IsReceive { get; set; }
    }
}
