//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GP_SystemEntities : DbContext
    {
        public GP_SystemEntities()
            : base("name=GP_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GP_Login> GP_Login { get; set; }
        public DbSet<GP_StudentsPersonalInformation2> GP_StudentsPersonalInformation2 { get; set; }
        public DbSet<GP_Professional_Base> GP_Professional_Base { get; set; }
        public DbSet<GP_StudentsRotaryInformation2> GP_StudentsRotaryInformation2 { get; set; }
        public DbSet<GP_SchoolInformation> GP_SchoolInformation { get; set; }
        public DbSet<GP_Questionnaire> GP_Questionnaire { get; set; }
        public DbSet<GP_RotarySchedule> GP_RotarySchedule { get; set; }
        public DbSet<GP_DeptManagement> GP_DeptManagement { get; set; }
        public DbSet<GP_Professional_Base_Dept> GP_Professional_Base_Dept { get; set; }
        public DbSet<GP_Disease_Register> GP_Disease_Register { get; set; }
        public DbSet<GP_Disease_Register2> GP_Disease_Register2 { get; set; }
        public DbSet<GP_SkillRequirement> GP_SkillRequirement { get; set; }
        public DbSet<GP_SkillRequirement2> GP_SkillRequirement2 { get; set; }
        public DbSet<GP_BigMedicalRecords2> GP_BigMedicalRecords2 { get; set; }
        public DbSet<GP_Area> GP_Area { get; set; }
        public DbSet<GP_City> GP_City { get; set; }
        public DbSet<GP_Province> GP_Province { get; set; }
        public DbSet<GP_TeachingActivities> GP_TeachingActivities { get; set; }
        public DbSet<GP_AttendanceManagement> GP_AttendanceManagement { get; set; }
        public DbSet<GP_AdviceFeedback> GP_AdviceFeedback { get; set; }
        public DbSet<GP_ReleaseNews> GP_ReleaseNews { get; set; }
        public DbSet<GP_NeiKeOption> GP_NeiKeOption { get; set; }
        public DbSet<GP_TiKuResult> GP_TiKuResult { get; set; }
        public DbSet<RotaryInformationJoin> RotaryInformationJoin { get; set; }
        public DbSet<GP_OutDept_Exam> GP_OutDept_Exam { get; set; }
        public DbSet<GP_Teachers_Appoint_Information> GP_Teachers_Appoint_Information { get; set; }
    
        public virtual int QuestionnaireChart(ObjectParameter sum, ObjectParameter one_a, ObjectParameter one_b, ObjectParameter one_c, ObjectParameter one_d, ObjectParameter one_e, ObjectParameter two_a, ObjectParameter two_b, ObjectParameter two_c, ObjectParameter two_d, ObjectParameter two_e, ObjectParameter three_a, ObjectParameter three_b, ObjectParameter three_c, ObjectParameter three_d, ObjectParameter three_e, ObjectParameter four_a, ObjectParameter four_b, ObjectParameter four_c, ObjectParameter four_d, ObjectParameter four_e, ObjectParameter five_a, ObjectParameter five_b, ObjectParameter five_c, ObjectParameter five_d, ObjectParameter five_e, ObjectParameter six_a, ObjectParameter six_b, ObjectParameter six_c, ObjectParameter six_d, ObjectParameter six_e, ObjectParameter seven_a, ObjectParameter seven_b, ObjectParameter seven_c, ObjectParameter seven_d, ObjectParameter seven_e, ObjectParameter eight_a, ObjectParameter eight_b, ObjectParameter eight_c, ObjectParameter eight_d, ObjectParameter eight_e, ObjectParameter nine_a, ObjectParameter nine_b, ObjectParameter nine_c, ObjectParameter nine_d, ObjectParameter nine_e, ObjectParameter ten_a, ObjectParameter ten_b, ObjectParameter ten_c, ObjectParameter ten_d, ObjectParameter ten_e, ObjectParameter eleven_a, ObjectParameter eleven_b, ObjectParameter eleven_c, ObjectParameter eleven_d, ObjectParameter eleven_e, ObjectParameter twelve_a, ObjectParameter twelve_b, ObjectParameter twelve_c, ObjectParameter twelve_d, ObjectParameter twelve_e, ObjectParameter thirteen_a, ObjectParameter thirteen_b, ObjectParameter thirteen_c, ObjectParameter thirteen_d, ObjectParameter thirteen_e, string training_base_code, string professional_base_code, string dept_code, string instructor)
        {
            var training_base_codeParameter = training_base_code != null ?
                new ObjectParameter("training_base_code", training_base_code) :
                new ObjectParameter("training_base_code", typeof(string));
    
            var professional_base_codeParameter = professional_base_code != null ?
                new ObjectParameter("professional_base_code", professional_base_code) :
                new ObjectParameter("professional_base_code", typeof(string));
    
            var dept_codeParameter = dept_code != null ?
                new ObjectParameter("dept_code", dept_code) :
                new ObjectParameter("dept_code", typeof(string));
    
            var instructorParameter = instructor != null ?
                new ObjectParameter("instructor", instructor) :
                new ObjectParameter("instructor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuestionnaireChart", sum, one_a, one_b, one_c, one_d, one_e, two_a, two_b, two_c, two_d, two_e, three_a, three_b, three_c, three_d, three_e, four_a, four_b, four_c, four_d, four_e, five_a, five_b, five_c, five_d, five_e, six_a, six_b, six_c, six_d, six_e, seven_a, seven_b, seven_c, seven_d, seven_e, eight_a, eight_b, eight_c, eight_d, eight_e, nine_a, nine_b, nine_c, nine_d, nine_e, ten_a, ten_b, ten_c, ten_d, ten_e, eleven_a, eleven_b, eleven_c, eleven_d, eleven_e, twelve_a, twelve_b, twelve_c, twelve_d, twelve_e, thirteen_a, thirteen_b, thirteen_c, thirteen_d, thirteen_e, training_base_codeParameter, professional_base_codeParameter, dept_codeParameter, instructorParameter);
        }
    }
}
